const catalogo = [
    {id:1 , nombre: "Remera", color: "Negra" , Precio: 800, img: '/images/remeras.jpg' ,stock: 3},
    {id:2 , nombre: "Remera", color: "Roja" , Precio: 800, stock: 3},
    {id:3 , nombre: "Remera", color: "Blanca" , Precio: 800, stock: 3},
    {id:4 , nombre: "Remera", color: "Azul" , Precio: 800, stock: 3},
    {id:5 , nombre: "Remera", color: "Gris" , Precio: 800, stock: 3},
    {id:6 , nombre: "Camisa", color: "Roja" , Precio: 800, stock: 3},
    {id:7 , nombre: "Camisa", color: "Negra" , Precio: 800, stock: 3},
    {id:8 , nombre: "Camisa", color: "Blanca" , Precio: 800, stock: 3},
    {id:9 , nombre: "Camisa", color: "Gris" , Precio: 800, stock: 3},
    {id:10 , nombre: "Camisa", color: "Azul" , Precio: 800, stock: 3},
    {id:11, nombre: "Pantalon", color: "Oscuro" , Precio: 800, stock: 3},
    {id:12, nombre: "Pantalon", color: "Negra" , Precio: 800, stock: 3},
    {id:13, nombre: "Pantalon", color: "Negra" , Precio: 800, stock: 3},
    {id:14, nombre: "Pantalon", color: "Claro" , Precio: 800, stock: 3},
    {id:15, nombre: "Pantalon", color: "Negra" , Precio: 800, stock: 3},
    {id:16, nombre: "Campera", color: "Negra" , Precio: 800, stock: 3},
    {id:17, nombre: "Campera", color: "Negra" , Precio: 800, stock: 3},
    {id:18, nombre: "Campera", color: "Negra" , Precio: 800, stock: 3},
    {id:19, nombre: "Campera", color: "Gris" , Precio: 800, stock: 3},
    {id:20, nombre: "Campera", color: "Negra" , Precio: 800, stock: 3}
];